import Head from "next/head";
import Header from "../components/Header";
import Landing from "../components/Landing";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Apple Redisgn</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="relative h-[200vh]">
                <Landing />
            </main>
            <section className="relative z-40 -mt-[100vh] min-h-screen bg-[#1b1b1b]">
                <div className="space-y-10 py-16">
                    <h1 className="text-center text-4xl font-medium tracking-wide text-white md:text-5xl">
                        New Promos
                    </h1>
                </div>
            </section>
        </div>
    );
}
